site_name: SDD
site_description: Data and Decision Sciences Engineering Program
site_url: https://supaerodatascience.github.io/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/SupaeroDataScience.github.io/master/src/favicon.ico'
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/SupaeroDataScience.github.io/master/src/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience
repo_url: https://github.com/SupaeroDataScience/

nav:
- Index: index.md
- Syllabus: syllabus.md
- Prospective students: students.md
- Info for students: infostudents.md
- Info for partners: partners.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
