site_name: SDD
site_description: Data and Decision Sciences Engineering Program
site_url: https://supaerodatascience.github.io/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/SupaeroDataScience.github.io/master/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/SupaeroDataScience.github.io/master/src/favicon.ico'
  features:
    - toc.autohide
    - navigation.sections

repo_name: SupaeroDataScience
repo_url: https://github.com/SupaeroDataScience/

nav:
- Index: index.md
- Prospective students: students.md
- Info for students: infostudents.md
- Info for partners: partners.md
- Syllabus:
    - Overview: syllabus.md
    - Machine Learning Algorithms: 'https://github.com/erachelson/MLclass'
    - Deep Learning: 'https://supaerodatascience.github.io/deep-learning/'
    - Reinforcement Learning: 'https://supaerodatascience.github.io/reinforcement-learning/'
    - Tools of Big Data: 'https://supaerodatascience.github.io/OBD/'

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
