site_name: SDD
site_description: Data and Decision Sciences Engineering Program
site_url: https://supaerodatascience.github.io/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/SupaeroDataScience.github.io/master/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/SupaeroDataScience.github.io/master/src/favicon.ico'
  features:
    - navigation.sections
    - navigation.expand

repo_name: SupaeroDataScience
repo_url: https://github.com/SupaeroDataScience/

nav:
- Home: index.md
- Prospective students: students.md
- Info for students: infostudents.md
- Info for partners: partners.md
- Syllabus:
    - Overview: syllabus.md
    - FSD301 TC:
      - Decision Theory: 'https://supaerodatascience.github.io/syllabus.html#fsd301'
      - Statistics: 'https://supaerodatascience.github.io/syllabus.html#fsd301'
      - Combinatorial Optimization: 'https://supaerodatascience.github.io/syllabus.html#fsd301'
      - Stochastic Optimization: 'https://supaerodatascience.github.io/stochastic/'
    - FSD311 AML:
      - Statistical Foundations of Machine Learning: https://supaerodatascience.github.io/stat-ml/
      - Machine Learning Algorithms: 'https://supaerodatascience.github.io/machine-learning/'
      - Deep Learning: 'https://supaerodatascience.github.io/deep-learning/'
      - Reinforcement Learning: 'https://supaerodatascience.github.io/reinforcement-learning/'
    - FSD312 ENUD: enud.md
    - FSD313 OBD: 'https://supaerodatascience.github.io/OBD/'
    - FSD314 Hackathon: hackathon.md
    - FSD319 Seminars: seminars.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
